### PR TITLE
Add support for tagged terms

### PR DESCRIPTION
**Pull request by curiousdannii**
Hi, I've added support for tagged terms (tag:term). I've also made the output more consistent, always making it return an array, and returning an empty array instead of an empty string, so I've bumped the version to 2.0.0.

Next will be OR support, but I needed this first.

### CODE REVIEW

**Comment by tatsuyaoiw** [comment]
Thank you for the contribution! This must be a great start to support nicer syntax to be used in real world use cases.

Two things I should mention for your PR: 

1. If an input is `'red bull "givesyouwings"'`, the term `givesyouwings` can't be marked as phrase because it does not contain spaces.
2. I understand using String object is sometimes very powerful and convenient, but it is less common and I prefer to avoid any surprises like `console.log(typeof str); // object` as much as possible. As you suggested this module to be bumped to version 2.0.0, I think it could also be possible to provide more explicit API, like the following:

```
[
  {
    term: 'red',
    phrase: false,
    tag: null
  },
  {
    term: 'bull',
    phrase: false,
    tag: null
  },
  {
    term: 'gives you wings',
    phrase: true,
    tag: null
  },
  {
    term: 'j. r. r. tolkien',
    phrase: true,
    tag: 'author'
  }
]
```

I shouldn't be so bad for those who want simple array given back.

```
tokenize('x y z').map(function(obj) {
  return obj.term;
});
```

What do you think?

**Comment by curiousdannii** [comment]
On 1, it won't be marked as a phrase. It checks for spaces, not whether quotes are used. 

On 2, I guess just returning simple objects could work. I kept it as strings so the tests would be simple (though using string objects had its own difficulties...)

**Comment by curiousdannii** [comment]
I ended up having additional trouble with the string objects, so I switched to plain objects. I only set phrase and tag when they are relevant however.

**Comment by tatsuyaoiw** [comment]
Thanks for updating! It looks neat!

> On 1, it won't be marked as a phrase. It checks for spaces, not whether quotes are used.

I think whenever the term is quoted, it should be treated as a phrase. It does't matter whether the term contains spaces or not. Here is a quote from [Google specs](https://support.google.com/websearch/answer/2466433):

> When you put a word or phrase in quotes, the results will only include pages with the same words in the same order as the ones inside the quotes. Only use this if you're looking for an exact word or phrase, otherwise you'll exclude many helpful results by mistake.

We also don't need to support single-quoted terms as phrases. So, my suggestion would be like the following.

```js
var result = {};

// Remove quotes
if ( /^".+"$/.test( term ) )
{
  term = _.trim( term, '" ' );
  result.phrase = true;
}

result.term = term;

if ( tag )
{
  result.tag = tag.slice( 0, -1 );
}
```

Cheers,

**Comment by curiousdannii** [comment]
Hmm, I guess it would be possible for someone to want to distinguish single words from quoted single words, and if we're still trying to be as close to Google as possible then we might as well do that. I don't see why we shouldn't also support single quoted phrases.

**Comment by tatsuyaoiw** [comment]
For me I have mostly used Apache Solr to implement search related features and Solr also uses double quotes as its phrase syntax. I don't have much experience working with other middleware or framework so I'm kind of curious if single quotes are also commonly used in search query to distinguish phrases. If there is demand to support it, I am totally fine not to follow Google, Solr or anything else:)

**Comment by curiousdannii** [comment]
[Some](https://cds.cern.ch/help/search-guide?ln=en#words-vs-phrases) [search](https://wiki.apache.org/solr/HelpOnSearching) [engines](http://www.washington.edu/willow/z3950.html#SEARCH) support single quotes, but admittedly not very many at all.

I guess my thinking is that anyone using this extension is going to be making a homebrew search system. They'd be using it because they don't have access to anything more sophisticated, so they probably don't have anything that would strip out punctuation. It's very easy for us to support single quoted phrases, it's unlikely to have false positives, and it prevents the quote being naively transformed into a `LIKE 'redbull` sql query.

Maybe a future version could allow for an options object to be passed in, which would specify whether to support single quoted phrases, and also whether to strip out punctuation on the boundaries of words. The default could be to not support single quoted phrases and to strip the quotes away, so that they would effectively be ignored. But until then I would like to support them.

**Comment by tatsuyaoiw** [comment]
OK now I'm convinced to support single quoted phrases. Also agreed on allowing to pass options. Thanks for sharing your knowledge around this topic.

**Comment by curiousdannii** [comment]
Single words will now be marked as phrases.

I think to be able to add OR support I'll want to switch to using a proper lexer rather than just a single regex, but I won't be working on it immediately.

**Comment by tatsuyaoiw** [comment]
Thanks!

**Comment by curiousdannii** [comment]
Are you going to publish it to npm?

**Comment by tatsuyaoiw** [comment]
Published! https://www.npmjs.com/package/search-text-tokenizer

**Pull request merged**
